<?php

namespace Cyclos\Tests\Apis;

use Cyclos\Api;
use Cyclos\Apis\PaymentsApi;
use PHPUnit\Framework\TestCase;

class PaymentsApiTest extends TestCase
{
    /**
     * @var PaymentsApi
     */
    public $payments;

    public function setUp()
    {
        parent::setUp();

        $this->payments = Api::getPayments();
    }

    public function tearDown()
    {
        unset($this->payments);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testPerform()
    {
        $response = $this->payments->perform([
            'amount' => 10,
            'description' => 'Cyclos library unit tests',
            'currency' => 'units',
            'subject' => 'demo2'
        ])->now();

        $this->assertTrue($response->isCool());
    }

    public function testPreview()
    {
        $response = $this->payments->preview([
            'amount' => 10,
            'description' => 'Cyclos library unit tests',
            'currency' => 'units',
            'subject' => 'demo2'
        ])->now();

        $this->assertTrue($response->isCool());
    }
}